sudo: false
language: python
python:
- '2.7'
- '3.6'
install:
- pip install -r requirements.txt
script:
- pylint monsoon setup.py
deploy:
  provider: pypi
  user: leonsp@ca.ibm.com
  password:
    secure: "c31vbSlGgha4zJCBc0ylcgAAdr4BFeCGU6kKfZR2SZACRZY2s3Ve9+78cFniY1SUTbVhZVFhxpfvLqPeA0lAPmLMcN8hXbUjTQYXdg9cvrrPw84f4lNt+Sd8PliIEOuYutormvM+tmN/R2OGl/M3c1SPnSpYM5O8rGakVbuSUY2Twfr3zypXLYpL8BAoQjAuJyetL4VomNIqPCuY4UIb3y/YdI5tFnj4xC1e8C/QAOC9vMHg9/HId2G+7/TfXiInFgjODKq8EObWmAZlTjPoX/MpyvS+ROfFVvcmJThRzVp7/lT3JfGC73hsDcVfS2XQXAZs9cZ3VKdIr12PQkeupZpcOWDZmlq04vYKo5NXFH2vVXxK9zk9Caoibpm86uxuk+DpW9uu/CR833/+wxiDju5ORFXKtabOrzGGQQFCcoivTyEiIgC82yT1BPo8ASASOaA/dtChfApzsUbot1s/bA8lIrqDIAMWVAYwIpBcSN4EgC2uVa7bqXOOEpWeuTelV+CG/c31lK8GMCCbkUY4+j6USBdZmwwqSBA3mYMWUnPv1/P8qUnJiRV80aTpBioFVngPbh+otAL2mpumKyHi+/uPPARXzVZsaRtfANZzYbClgZ8MppMLaHCzvS9smetXnHBeplvDvkXuhLxwJRe0dLMaDE1Nvd90z/24ElARztk="
  server: https://na.artifactory.swg-devops.com/artifactory/api/pypi/apset-pypi-local
  on:
    python: '2.7'
    repo: apset/monsoon
    tags: true
notifications:
  slack:
    secure: EvcFxI8CddcjTjRPQYlh4SSyedYV55RRRyFBfuT9bpb0WRdmsOfsdyzCyJ2LjcqKlJ9IJIXd2oS9RQniSLgoc77KRyFhyX3ZnYr/v+d2Dk/IVWF7gDyMZ1UaYMhmnyXgX3SrUnu3uL5ID3KjsfQh5C7fATlj+M6k1qBLrpSJ8Q2rSkDEGOdtLKNAPp/eamXXizZcNUXmLXqqKhtOB8hvAtzVaXNxypfSkYQu9YpqS8GWwnK9EWgjMw0axPJ80iE9wlXDcOax5DdROfhbz9E8NZjaCSjadqPij3OebINI0ToRYlCvtjOQ32nx3av1rJV5rZ33/vn2Uq15RBOW/dkTI4ilQ+6ymlKVuDs+PsLzpYXmkT2XZJo+KXENUc+1MYxhpewmtio/KpV/1ecbtpzWFeFM/beLmrASePoKOgiNvH66b+ifSP4sQsFBZMhccF5px6+kiW3i8A1jY3mEyO9Ubh0jRl4bRdhaMqS5CqM5B7Vs86xiWoZqF+XEE4CPTT5oKTWptLEdXKTkJHkOLHohjjYKu2YT41Bm7jIng3CXD2Ej26bg65VHs78v/g/z5qimxrBgW1VgbUST+PpCyjb2CPNoAU++QgdstHX8Z4usPi2PpvP/zm+hGH4yCIDKvbSapGyC/aemlNQm2v7Pe+qNNFpqv/eVAn9YBS2kmMeNfA=B0imf80sSJWy
