sudo: false
language: python
python:
- '2.7'
- '3.6'
install:
- pip install -r requirements.txt
script:
- pylint monsoon setup.py
deploy:
  provider: pypi
  user: leonsp@ca.ibm.com
  password:
    secure: c31vbSlGgha4zJCBc0ylcgAAdr4BFeCGU6kKfZR2SZACRZY2s3Ve9+78cFniY1SUTbVhZVFhxpfvLqPeA0lAPmLMcN8hXbUjTQYXdg9cvrrPw84f4lNt+Sd8PliIEOuYutormvM+tmN/R2OGl/M3c1SPnSpYM5O8rGakVbuSUY2Twfr3zypXLYpL8BAoQjAuJyetL4VomNIqPCuY4UIb3y/YdI5tFnj4xC1e8C/QAOC9vMHg9/HId2G+7/TfXiInFgjODKq8EObWmAZlTjPoX/MpyvS+ROfFVvcmJThRzVp7/lT3JfGC73hsDcVfS2XQXAZs9cZ3VKdIr12PQkeupZpcOWDZmlq04vYKo5NXFH2vVXxK9zk9Caoibpm86uxuk+DpW9uu/CR833/+wxiDju5ORFXKtabOrzGGQQFCcoivTyEiIgC82yT1BPo8ASASOaA/dtChfApzsUbot1s/bA8lIrqDIAMWVAYwIpBcSN4EgC2uVa7bqXOOEpWeuTelV+CG/c31lK8GMCCbkUY4+j6USBdZmwwqSBA3mYMWUnPv1/P8qUnJiRV80aTpBioFVngPbh+otAL2mpumKyHi+/uPPARXzVZsaRtfANZzYbClgZ8MppMLaHCzvS9smetXnHBeplvDvkXuhLxwJRe0dLMaDE1Nvd90z/24ElARztk=
  server: https://na.artifactory.swg-devops.com/artifactory/api/pypi/apset-pypi-local
  on:
    python: '2.7'
    repo: apset/monsoon
    tags: true
notifications:
  slack:
    secure: CU+UAAAUCyKr8K/79Mnkf3UXA1az1/B5cchkgpeH/fuBTMVuNVOpdpMuPCRABkAiM409wyDh6apBT9GcV/l6HWHWrO4Z75FKSd5lgukboNEmMbtveEsDdnxJ4MIa47pc5Oqi0sSFwBotcalyT2pFjTuBIecnR0yDDOhaQj5rK229qo4BfJwsV7yv9UsXZkdQCbFEVddnGQHzA0zkNjxjLkJB4oEu9g0X6+McZfn8VfLkrrjkzA4IZTrXZ3wSInUfgC+Q/2xH58531weNR0RYwl8kxnZ98SkMBX3xVkMTD+IP8pzvkFZu6QnUyO5zc4ALV9pgq8pzELeju2AUWFT3pjZYFB3a60PQjHUTh37YOGZDTY/u/QR8uEJj9pmptDP40z4AITSNtlyPE8RyglQPJP0FQnIfdcbOdTxCXo9f5XUPOFKDEIOUa00vfKMdu/A9SEgSdsCE2uPs8FQR/GSYP9nwWmMMP/FoCJ7s6yBV5u4FJY7TE4/U0UJhxrfXEnfiepjURfGWhYbyfPD+S5wz3j+2OFbuDUQlm5XdtUXjucT48JVRgD6qvzIWHo4u8yrfz1+BAbqe292CPjiUST35R5XuYjt+WdkjsMO8CPW+M8vtuJm82xNVfCGPIixaFFB03tkE3+98sZRUrhNn7dvgs5q2hDQETavlKUVLee68amo=
